name: Deploy PR to Preview

on:
  workflow_dispatch:
  pull_request:
    branches-ignore:    
      - revert-logger
      - aa
    paths:
      - "**.md"


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
